"""add_scenario_fields

Revision ID: e02bb8c83b9d
Revises: dc27a30675c3
Create Date: 2026-01-26 14:38:57.151530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02bb8c83b9d'
down_revision = 'dc27a30675c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_email_key'), 'accounts', type_='unique')
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.create_unique_constraint(op.f('accounts_email_key'), 'accounts', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
